#!/bin/bash

# display the status of the battery with time until charged/depletion or "try again" if zero rate

notify-send -i terminal "$(acpi -b | awk -F', ' '/zero rate/ { print "  try again in a second"; exit } /Discharging|Charging/ { print "  " $3 ; exit }')"
